[package]
name = "fmlisp"
version = "0.1.0"
authors = ["Elia Scotto @eliascotto"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fnv = "1.0.7"
itertools = "0.12.0"
regex = "1.10.2"
rustyline = "13.0.0"
if_chain = "1.0.2"
